services:
    app:
        container_name: my-laravel-app
        image: your-dockerhub-username/my-laravel-app:latest
        build:
            context: .
            target: production
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
        ports:
            - 8080:8080